/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analyses */
        get: operations["list_analyses_api_analyses_get"];
        put?: never;
        /** Create Analysis */
        post: operations["create_analysis_api_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Batch */
        post: operations["create_batch_api_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_api_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rate-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rate Card */
        get: operations["get_rate_card_api_rate_card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_api_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quote Check */
        post: operations["quote_check_api_analyses__analysis_id__quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Report */
        get: operations["model_report_api_model_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Ad */
        Ad: {
            /** Code */
            code: string;
            /** Taken At */
            taken_at: string;
            /** Disclosed */
            disclosed: boolean;
            /** Brand */
            brand: string | null;
            /** Topic */
            topic: string | null;
        };
        /** Analysis */
        Analysis: {
            /** Id */
            id: string;
            /** Handle */
            handle: string;
            inputs: components["schemas"]["Inputs"];
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "out_of_scope" | "failed";
            /** Step */
            step: number;
            /** Steps */
            steps: string[];
            /** Reason */
            reason?: string | null;
            /** Error */
            error?: string | null;
            result?: components["schemas"]["Report"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /** AnalysisRequest */
        AnalysisRequest: {
            /** Category */
            category?: string | null;
            /** Quote */
            quote?: number | null;
            /** Budget */
            budget?: number | null;
            /** Handle */
            handle: string;
        };
        /** AnalysisSummary */
        AnalysisSummary: {
            /** Id */
            id: string;
            /** Handle */
            handle: string;
            /** Status */
            status: string;
            /** Call */
            call: string | null;
            /** Fair */
            fair: number | null;
            /** Verdict */
            verdict: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Audience */
        Audience: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "Real audience" | "Some fake activity" | "Mostly fake";
            /** Failed Families */
            failed_families: string[];
            /** Flags */
            flags: components["schemas"]["Flag"][];
            /** Signals */
            signals: {
                [key: string]: number | null;
            };
            /** Medians */
            medians: {
                [key: string]: number;
            };
            /** Warnings */
            warnings: string[];
            mix: components["schemas"]["Mix"];
        };
        /** Batch */
        Batch: {
            /** Id */
            id: string;
            inputs: components["schemas"]["Inputs"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Total */
            total: number;
            /** Done */
            done: number;
            /** Rows */
            rows: components["schemas"]["BatchRow"][];
        };
        /** BatchRequest */
        BatchRequest: {
            /** Category */
            category?: string | null;
            /** Quote */
            quote?: number | null;
            /** Budget */
            budget?: number | null;
            /** Handles */
            handles: string[];
        };
        /** BatchRow */
        BatchRow: {
            /** Handle */
            handle: string;
            /** Analysis Id */
            analysis_id: string;
            /** Status */
            status: string;
            /** Call */
            call: string | null;
            /** Verdict */
            verdict: string | null;
            /** Fair */
            fair: number | null;
            /** Low */
            low: number | null;
            /** High */
            high: number | null;
            /** Cost Per 1K */
            cost_per_1k: number | null;
            /** Expected Views */
            expected_views: number | null;
            /** Reason */
            reason: string | null;
        };
        /** BrandTag */
        BrandTag: {
            /** Code */
            code: string;
            /** Taken At */
            taken_at: string;
            /** Brand */
            brand: string;
            /** Topic */
            topic: string | null;
        };
        /** CategoryRate */
        CategoryRate: {
            /** Category */
            category: string;
            /** N */
            n: number;
            per_1k: components["schemas"]["Per1k"];
            /** Typical Price */
            typical_price: number;
            /** Typical Views */
            typical_views: number;
        };
        /** Cheaper */
        Cheaper: {
            /** Handle */
            handle: string;
            /** Per 1K Views */
            per_1k_views: number;
            /** Views */
            views: number;
            /** Price */
            price: number;
        };
        /** Comparable */
        Comparable: {
            /** Handle */
            handle: string;
            /** Price */
            price: number;
            /** Views */
            views: number;
            /** Followers */
            followers: number;
            /** Category */
            category: string;
            /** Per 1K Views */
            per_1k_views: number;
        };
        /** Competitor */
        Competitor: {
            /** Brand */
            brand: string | null;
            /** Days */
            days: number;
            /** Code */
            code: string;
        };
        /** Created */
        Created: {
            /** Id */
            id: string;
        };
        /** Decision */
        Decision: {
            /**
             * Call
             * @enum {string}
             */
            call: "Go" | "Negotiate" | "Avoid";
            /** Reasons */
            reasons: string[];
        };
        /** Delivery */
        Delivery: {
            /** Views */
            views: number[];
            /** Likes */
            likes: number;
            /** Comments */
            comments: number;
            /** Cost Per 1K */
            cost_per_1k: number;
            /** Category Cost Per 1K */
            category_cost_per_1k: number | null;
        };
        /** Engagement */
        Engagement: {
            /** Rate */
            rate: number;
            /**
             * Band
             * @enum {string}
             */
            band: "small" | "medium" | "big";
            /** Band Median */
            band_median: number | null;
            /** Percentile */
            percentile: number | null;
        };
        /** Flag */
        Flag: {
            /** Signal */
            signal: string;
            /** Family */
            family: string;
            /** Value */
            value: number;
            /** Median */
            median: number;
            /** Text */
            text: string;
        };
        /** FollowerPoint */
        FollowerPoint: {
            /** At */
            at: string;
            /** Followers */
            followers: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Inputs */
        Inputs: {
            /** Category */
            category?: string | null;
            /** Quote */
            quote?: number | null;
            /** Budget */
            budget?: number | null;
        };
        /** Language */
        Language: {
            /** Language */
            language: string;
            /** Share */
            share: number;
        };
        /** Meta */
        Meta: {
            /** Categories */
            categories: string[];
            /** Range Coverage */
            range_coverage: number | null;
        };
        /** Mix */
        Mix: {
            /** Top */
            top: number;
            /** Fake */
            fake: number;
            /** Brands */
            brands: number;
            /** Creators */
            creators: number;
            /** People */
            people: number;
            /** Languages */
            languages: components["schemas"]["Language"][];
        };
        /** ModelReport */
        ModelReport: {
            /** Validation */
            validation: {
                [key: string]: unknown;
            } | null;
            /** Redteam */
            redteam: {
                [key: string]: unknown;
            } | null;
        };
        /** Negotiation */
        Negotiation: {
            /** Start */
            start: number;
            /** Target */
            target: number;
            /** Walk Away */
            walk_away: number;
            /** Lines */
            lines: string[];
        };
        /** Niche */
        Niche: {
            /** Category */
            category: string;
            /** Topics */
            topics: {
                [key: string]: number;
            };
            /** Product */
            product: string | null;
            /** Fit */
            fit: ("strong" | "good" | "some" | "weak") | null;
            /** Fit Share */
            fit_share: number | null;
        };
        /** PaidRatio */
        PaidRatio: {
            /** N */
            n: number;
            /** Ratio */
            ratio: number | null;
            /** Typical Ratio */
            typical_ratio: number;
        };
        /** Per1k */
        Per1k: {
            /** P25 */
            p25: number;
            /** Median */
            median: number;
            /** P75 */
            p75: number;
        };
        /** Placement */
        Placement: {
            /** Reels */
            reels: components["schemas"]["ReelPoint"][];
            /** Followers History */
            followers_history: components["schemas"]["FollowerPoint"][];
            /** Typical Views */
            typical_views: number;
            /** Bad Reel Views */
            bad_reel_views: number;
            /** Hits Last 10 */
            hits_last_10: number;
            /** Trend */
            trend: number | null;
            paid: components["schemas"]["PaidRatio"];
            collab: components["schemas"]["Ratio"];
            /** Ads */
            ads: components["schemas"]["Ad"][];
            /** Brand Tags */
            brand_tags: components["schemas"]["BrandTag"][];
            /** N Reposts */
            n_reposts: number;
        };
        /** Price */
        Price: {
            /** Market */
            market: number;
            /** Fair */
            fair: number;
            /** Low */
            low: number;
            /** High */
            high: number;
            /** Collab Factor */
            collab_factor: number;
            /** Genuine Share */
            genuine_share: number;
            /** Waterfall */
            waterfall: components["schemas"]["WaterfallStep"][];
            /** Comparables */
            comparables: components["schemas"]["Comparable"][];
            delivery: components["schemas"]["Delivery"];
        };
        /** Profile */
        Profile: {
            /** Full Name */
            full_name: string;
            /** Followers */
            followers: number;
            /** Following */
            following: number;
            /** Posts */
            posts: number;
            /** Bio */
            bio: string;
            /** Is Verified */
            is_verified: boolean;
        };
        /** QuoteCheck */
        QuoteCheck: {
            /** Quote */
            quote: number;
            /**
             * Position
             * @enum {string}
             */
            position: "below" | "within" | "above";
            /** Difference */
            difference: number;
            /** Counter Offer */
            counter_offer: number;
            /** Talking Points */
            talking_points: string[];
        };
        /** QuoteRequest */
        QuoteRequest: {
            /** Quote */
            quote: number;
        };
        /** RateCard */
        RateCard: {
            /** Categories */
            categories: components["schemas"]["CategoryRate"][];
        };
        /** Ratio */
        Ratio: {
            /** N */
            n: number;
            /** Ratio */
            ratio: number | null;
        };
        /** ReelPoint */
        ReelPoint: {
            /** Code */
            code: string;
            /** Taken At */
            taken_at: string;
            /** Views */
            views: number;
            /** Likes */
            likes: number;
            /** Comments */
            comments: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "own" | "paid" | "collab" | "repost";
            /** Thumbnail */
            thumbnail: string;
        };
        /** Report */
        Report: {
            /** Handle */
            handle: string;
            profile: components["schemas"]["Profile"];
            /** Fetched At */
            fetched_at: string;
            /** Category */
            category: string;
            /**
             * Category Source
             * @enum {string}
             */
            category_source: "wldd" | "gemini";
            /** Face Share */
            face_share: number | null;
            decision: components["schemas"]["Decision"];
            price: components["schemas"]["Price"];
            audience: components["schemas"]["Audience"];
            engagement: components["schemas"]["Engagement"];
            placement: components["schemas"]["Placement"];
            niche: components["schemas"]["Niche"];
            /** Worth Reaching */
            worth_reaching: string;
            competitor: components["schemas"]["Competitor"] | null;
            /** Cheaper */
            cheaper: components["schemas"]["Cheaper"][];
            /** Suggested */
            suggested: string[];
            negotiation: components["schemas"]["Negotiation"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WaterfallStep */
        WaterfallStep: {
            /** Step */
            step: string;
            /** Amount */
            amount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_analyses_api_analyses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"][];
                };
            };
        };
    };
    create_analysis_api_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Created"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_batch_api_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Created"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_api_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rate_card_api_rate_card_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateCard"];
                };
            };
        };
    };
    get_analysis_api_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_check_api_analyses__analysis_id__quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteCheck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    model_report_api_model_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelReport"];
                };
            };
        };
    };
}
